// <auto-generated />
using System;
using Kolokwium2Poprawa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium2Poprawa.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250611125719_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Backpack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("Backpack");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0,
                            CharacterId = 1,
                            ItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0,
                            CharacterId = 3,
                            ItemId = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0,
                            CharacterId = 2,
                            ItemId = 2
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentWeight = 3,
                            FirstName = "John",
                            LastName = "Doe",
                            MaxWeight = 30
                        },
                        new
                        {
                            Id = 2,
                            CurrentWeight = 3,
                            FirstName = "Jane",
                            LastName = "Doe",
                            MaxWeight = 20
                        },
                        new
                        {
                            Id = 3,
                            CurrentWeight = 3,
                            FirstName = "Julie",
                            LastName = "Doe",
                            MaxWeight = 40
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Character_Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("TitleId");

                    b.ToTable("Character_Title");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcquiredAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CharacterId = 1,
                            TitleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AcquiredAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CharacterId = 2,
                            TitleId = 2
                        },
                        new
                        {
                            Id = 3,
                            AcquiredAt = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CharacterId = 3,
                            TitleId = 3
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple",
                            Weight = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sword",
                            Weight = 5
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cactus",
                            Weight = 5
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Title");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Slayer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "The Slayer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "The The Slayer"
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Backpack", b =>
                {
                    b.HasOne("Kolokwium2Poprawa.Models.Character", "Character")
                        .WithMany("Backpacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2Poprawa.Models.Item", "Item")
                        .WithMany("Backpacks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Character_Title", b =>
                {
                    b.HasOne("Kolokwium2Poprawa.Models.Character", "Character")
                        .WithMany("Titles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2Poprawa.Models.Title", "Title")
                        .WithMany("Title_Characters")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Character", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Item", b =>
                {
                    b.Navigation("Backpacks");
                });

            modelBuilder.Entity("Kolokwium2Poprawa.Models.Title", b =>
                {
                    b.Navigation("Title_Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
